### ISSUE TITLE
Bottom of landing cut off on Firefox 51

### ISSUE THREAD

**Issue by TheInitializer** [RyanFitzgerald/devportfolio-template#4] opened 2017-03-20 22:02 UTC
![image](https://cloud.githubusercontent.com/assets/6720845/24123794/5ac2cc88-0d97-11e7-97ca-51576f335849.png)

**Comment by RyanFitzgerald** [comment] 2017-03-21 00:42
I haven't been able to recreate the issue myself in Firefox 51. Is the bottom completely cut off or is it simply out of the viewport until you scroll down?

**Comment by RyanFitzgerald** [comment] 2017-03-21 14:21
Going to close this for now since I can't seem to recreate it and there aren't any steps to reproduce. If others notice the issue as well, feel free to reopen!

**Comment by TheInitializer** [comment] 2017-03-21 20:16
The bottom is out of the viewport until you scroll down. My screen is 1366x768 so that may be the problem?

**Comment by RyanFitzgerald** [comment] 2017-03-21 20:21
Hmm alright, I've reopened it. I'll look into finding a solution for that; more than likely just setting that to the viewport height. Thanks!

**Comment by TheInitializer** [comment] 2017-03-21 20:35
After measuring with ShareX's handy ruler tool, it appears that my browser's viewport height is 659 px. It would be useful to decrease the min-height as the landing would still look good below 700px.

**Comment by RyanFitzgerald** [comment] 2017-03-21 23:04
Issue fixed in 1.1.2.

**Closed by RyanFitzgerald** 2017-03-21 23:04 UTC
